name: briskly
recipe: wordpress

config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: false
  composer_version: "2.3.5"

services:
  database:
    type: mariadb
    creds:
      user: wordpress
      password: wordpress
      database: wordpress
  appserver:
    build:
      - composer install
  theme:
    type: node:14
    build:
      - npm install --no-save

tooling:
  npm:
    service: theme
  node:
    service: theme

