on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    permissions: write-all
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer dependencies
      uses: php-actions/composer@v5

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        protocol: ftp
        port: ${{ secrets.FTPPORT }}
        username: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASS }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
